// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace ProbSqlite.Migrations
{
    [DbContext(typeof(ProbContext))]
    class ProbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11");

            modelBuilder.Entity("ProbSqlite.PairToPair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Draw")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstPair")
                        .HasColumnType("TEXT");

                    b.Property<int>("Lose")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecondPair")
                        .HasColumnType("TEXT");

                    b.Property<int>("Win")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PairToPairs");
                });
#pragma warning restore 612, 618
        }
    }
}
